export default {
    UPDATE_FECHA: "UPDATE_FECHA",
    GET_ESTRENOS: "GET_ESTRENOS",
    GET_ESTRENOS_PENDING: "GET_ESTRENOS_PENDING",
    GET_ESTRENOS_FULFILLED: "GET_ESTRENOS_FULFILLED", 
    GET_ESTRENOS_REJECTED: "GET_ESTRENOS_REJECTED",

    // Acciones para próximos estrenos
    GET_PROXIMOS_ESTRENOS: "GET_PROXIMOS_ESTRENOS",
    GET_PROXIMOS_ESTRENOS_FULFILLED: "GET_PROXIMOS_ESTRENOS_FULFILLED",
    GET_PROXIMOS_ESTRENOS_PENDING: "GET_PROXIMOS_ESTRENOS_PENDING",
    GET_PROXIMOS_ESTRENOS_REJECTED: "GET_PROXIMOS_ESTRENOS_REJECTED",

    // Acciones para créditos
    GET_CREDITOS: "GET_CREDITOS", 
    GET_CREDITOS_FULFILLED: "GET_CREDITOS_FULFILLED", 
    GET_CREDITOS_PENDING: "GET_CREDITOS_PENDING", 
    GET_CREDITOS_REJECTED: "GET_CREDITOS_REJECTED", 

    // Acciones para el detalle de la película
    GET_PELICULA_DETALLE: "GET_PELICULA_DETALLE", 
    GET_PELICULA_DETALLE_FULFILLED: "GET_PELICULA_DETALLE_FULFILLED", 
    GET_PELICULA_DETALLE_PENDING: "GET_PELICULA_DETALLE_PENDING", 
    GET_PELICULA_DETALLE_REJECTED: "GET_PELICULA_DETALLE_REJECTED"
}