export default {
    UPDATE_FECHA: "UPDATE_FECHA",
    GET_PROXIMOS_ESTRENOS: "GET_PROXIMOS_ESTRENOS",
    GET_ESTRENOS: "GET_ESTRENOS",
    GET_ESTRENOS_PENDING: "GET_ESTRENOS_PENDING",
    GET_ESTRENOS_FULFILLED: "GET_ESTRENOS_FULFILLED", 
    GET_ESTRENOS_REJECTED: "GET_ESTRENOS_REJECTED"
}